// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace UiPath.Web.Client202010.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    public partial class EntryPointDataVariationDto
    {
        /// <summary>
        /// Initializes a new instance of the EntryPointDataVariationDto class.
        /// </summary>
        public EntryPointDataVariationDto()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the EntryPointDataVariationDto class.
        /// </summary>
        /// <param name="contentType">Possible values include: 'Json'</param>
        public EntryPointDataVariationDto(string content = default(string), EntryPointDataVariationDtoContentType? contentType = default(EntryPointDataVariationDtoContentType?), long? id = default(long?))
        {
            Content = content;
            ContentType = contentType;
            Id = id;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Content")]
        public string Content { get; set; }

        /// <summary>
        /// Gets or sets possible values include: 'Json'
        /// </summary>
        [JsonProperty(PropertyName = "ContentType")]
        public EntryPointDataVariationDtoContentType? ContentType { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Id")]
        public long? Id { get; set; }

    }
}
