// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace UiPath.Web.Client202010.Models
{
    using Newtonsoft.Json;
    using Newtonsoft.Json.Converters;
    using System.Runtime;
    using System.Runtime.Serialization;

    /// <summary>
    /// Defines values for LicenseRuntimeDtoMachineType.
    /// </summary>
    [JsonConverter(typeof(StringEnumConverter))]
    public enum LicenseRuntimeDtoMachineType
    {
        [EnumMember(Value = "Standard")]
        Standard,
        [EnumMember(Value = "Template")]
        Template
    }
    internal static class LicenseRuntimeDtoMachineTypeEnumExtension
    {
        internal static string ToSerializedValue(this LicenseRuntimeDtoMachineType? value)
        {
            return value == null ? null : ((LicenseRuntimeDtoMachineType)value).ToSerializedValue();
        }

        internal static string ToSerializedValue(this LicenseRuntimeDtoMachineType value)
        {
            switch( value )
            {
                case LicenseRuntimeDtoMachineType.Standard:
                    return "Standard";
                case LicenseRuntimeDtoMachineType.Template:
                    return "Template";
            }
            return null;
        }

        internal static LicenseRuntimeDtoMachineType? ParseLicenseRuntimeDtoMachineType(this string value)
        {
            switch( value )
            {
                case "Standard":
                    return LicenseRuntimeDtoMachineType.Standard;
                case "Template":
                    return LicenseRuntimeDtoMachineType.Template;
            }
            return null;
        }
    }
}
