// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace UiPath.Web.Client202010.Models
{
    using Newtonsoft.Json;
    using Newtonsoft.Json.Converters;
    using System.Runtime;
    using System.Runtime.Serialization;

    /// <summary>
    /// Defines values for PackageDtoProjectType.
    /// </summary>
    [JsonConverter(typeof(StringEnumConverter))]
    public enum PackageDtoProjectType
    {
        [EnumMember(Value = "Undefined")]
        Undefined,
        [EnumMember(Value = "Process")]
        Process,
        [EnumMember(Value = "ProcessLibrary")]
        ProcessLibrary,
        [EnumMember(Value = "BusinessProcess")]
        BusinessProcess,
        [EnumMember(Value = "BusinessProcessLibrary")]
        BusinessProcessLibrary,
        [EnumMember(Value = "TestAutomationProcess")]
        TestAutomationProcess
    }
    internal static class PackageDtoProjectTypeEnumExtension
    {
        internal static string ToSerializedValue(this PackageDtoProjectType? value)
        {
            return value == null ? null : ((PackageDtoProjectType)value).ToSerializedValue();
        }

        internal static string ToSerializedValue(this PackageDtoProjectType value)
        {
            switch( value )
            {
                case PackageDtoProjectType.Undefined:
                    return "Undefined";
                case PackageDtoProjectType.Process:
                    return "Process";
                case PackageDtoProjectType.ProcessLibrary:
                    return "ProcessLibrary";
                case PackageDtoProjectType.BusinessProcess:
                    return "BusinessProcess";
                case PackageDtoProjectType.BusinessProcessLibrary:
                    return "BusinessProcessLibrary";
                case PackageDtoProjectType.TestAutomationProcess:
                    return "TestAutomationProcess";
            }
            return null;
        }

        internal static PackageDtoProjectType? ParsePackageDtoProjectType(this string value)
        {
            switch( value )
            {
                case "Undefined":
                    return PackageDtoProjectType.Undefined;
                case "Process":
                    return PackageDtoProjectType.Process;
                case "ProcessLibrary":
                    return PackageDtoProjectType.ProcessLibrary;
                case "BusinessProcess":
                    return PackageDtoProjectType.BusinessProcess;
                case "BusinessProcessLibrary":
                    return PackageDtoProjectType.BusinessProcessLibrary;
                case "TestAutomationProcess":
                    return PackageDtoProjectType.TestAutomationProcess;
            }
            return null;
        }
    }
}
