// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace UiPath.Web.Client202010.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    /// <summary>
    /// Simple Task entity for external access
    /// </summary>
    public partial class TaskDto
    {
        /// <summary>
        /// Initializes a new instance of the TaskDto class.
        /// </summary>
        public TaskDto()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the TaskDto class.
        /// </summary>
        /// <param name="status">Gets or sets the status of this task. Possible
        /// values include: 'Unassigned', 'Pending', 'Completed'</param>
        /// <param name="taskCatalogName">Gets or sets the task
        /// catalog/category of the task</param>
        /// <param name="title">Gets or sets title of this task.</param>
        /// <param name="type">Gets or sets type of this task. Possible values
        /// include: 'FormTask', 'ExternalTask', 'DocumentValidationTask',
        /// 'DocumentClassificationTask'</param>
        /// <param name="priority">Gets or sets priority of this task. Possible
        /// values include: 'Low', 'Medium', 'High', 'Critical'</param>
        /// <param name="assignedToUserId">Gets the id of the actual assigned
        /// user, if any.</param>
        /// <param name="creatorUserId">Gets the id of the user who created the
        /// task.</param>
        /// <param name="lastModifierUserId">Gets the id of the user who
        /// modified the task, if any.</param>
        /// <param name="creationTime">Gets or sets time at which this task was
        /// created.</param>
        /// <param name="lastModificationTime">Gets or sets time at which this
        /// task was last modified.</param>
        /// <param name="organizationUnitId">Gets or sets the
        /// folder/organization-unit id.</param>
        /// <param name="externalTag">Identifier of external system where this
        /// task is handled</param>
        public TaskDto(TaskDtoStatus? status = default(TaskDtoStatus?), UserLoginInfoDto assignedToUser = default(UserLoginInfoDto), string taskCatalogName = default(string), bool? isCompleted = default(bool?), string title = default(string), TaskMetadataDtoType? type = default(TaskMetadataDtoType?), TaskMetadataDtoPriority? priority = default(TaskMetadataDtoPriority?), long? assignedToUserId = default(long?), long? creatorUserId = default(long?), long? lastModifierUserId = default(long?), System.DateTime? creationTime = default(System.DateTime?), System.DateTime? lastModificationTime = default(System.DateTime?), long? organizationUnitId = default(long?), string externalTag = default(string), long? id = default(long?))
        {
            Status = status;
            AssignedToUser = assignedToUser;
            TaskCatalogName = taskCatalogName;
            IsCompleted = isCompleted;
            Title = title;
            Type = type;
            Priority = priority;
            AssignedToUserId = assignedToUserId;
            CreatorUserId = creatorUserId;
            LastModifierUserId = lastModifierUserId;
            CreationTime = creationTime;
            LastModificationTime = lastModificationTime;
            OrganizationUnitId = organizationUnitId;
            ExternalTag = externalTag;
            Id = id;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// Gets or sets the status of this task. Possible values include:
        /// 'Unassigned', 'Pending', 'Completed'
        /// </summary>
        [JsonProperty(PropertyName = "Status")]
        public TaskDtoStatus? Status { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "AssignedToUser")]
        public UserLoginInfoDto AssignedToUser { get; set; }

        /// <summary>
        /// Gets or sets the task catalog/category of the task
        /// </summary>
        [JsonProperty(PropertyName = "TaskCatalogName")]
        public string TaskCatalogName { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "IsCompleted")]
        public bool? IsCompleted { get; set; }

        /// <summary>
        /// Gets or sets title of this task.
        /// </summary>
        [JsonProperty(PropertyName = "Title")]
        public string Title { get; set; }

        /// <summary>
        /// Gets or sets type of this task. Possible values include:
        /// 'FormTask', 'ExternalTask', 'DocumentValidationTask',
        /// 'DocumentClassificationTask'
        /// </summary>
        [JsonProperty(PropertyName = "Type")]
        public TaskMetadataDtoType? Type { get; set; }

        /// <summary>
        /// Gets or sets priority of this task. Possible values include: 'Low',
        /// 'Medium', 'High', 'Critical'
        /// </summary>
        [JsonProperty(PropertyName = "Priority")]
        public TaskMetadataDtoPriority? Priority { get; set; }

        /// <summary>
        /// Gets the id of the actual assigned user, if any.
        /// </summary>
        [JsonProperty(PropertyName = "AssignedToUserId")]
        public long? AssignedToUserId { get; set; }

        /// <summary>
        /// Gets the id of the user who created the task.
        /// </summary>
        [JsonProperty(PropertyName = "CreatorUserId")]
        public long? CreatorUserId { get; set; }

        /// <summary>
        /// Gets the id of the user who modified the task, if any.
        /// </summary>
        [JsonProperty(PropertyName = "LastModifierUserId")]
        public long? LastModifierUserId { get; set; }

        /// <summary>
        /// Gets or sets time at which this task was created.
        /// </summary>
        [JsonProperty(PropertyName = "CreationTime")]
        public System.DateTime? CreationTime { get; set; }

        /// <summary>
        /// Gets or sets time at which this task was last modified.
        /// </summary>
        [JsonProperty(PropertyName = "LastModificationTime")]
        public System.DateTime? LastModificationTime { get; set; }

        /// <summary>
        /// Gets or sets the folder/organization-unit id.
        /// </summary>
        [JsonProperty(PropertyName = "OrganizationUnitId")]
        public long? OrganizationUnitId { get; set; }

        /// <summary>
        /// Gets or sets identifier of external system where this task is
        /// handled
        /// </summary>
        [JsonProperty(PropertyName = "ExternalTag")]
        public string ExternalTag { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Id")]
        public long? Id { get; set; }

    }
}
