// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace UiPath.Web.Client202010.Models
{
    using Microsoft.Rest;
    using Newtonsoft.Json;
    using System.Linq;

    public partial class WebhookEventDto
    {
        /// <summary>
        /// Initializes a new instance of the WebhookEventDto class.
        /// </summary>
        public WebhookEventDto()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the WebhookEventDto class.
        /// </summary>
        public WebhookEventDto(string eventType)
        {
            EventType = eventType;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "EventType")]
        public string EventType { get; set; }

        /// <summary>
        /// Validate the object.
        /// </summary>
        /// <exception cref="ValidationException">
        /// Thrown if validation fails
        /// </exception>
        public virtual void Validate()
        {
            if (EventType == null)
            {
                throw new ValidationException(ValidationRules.CannotBeNull, "EventType");
            }
            if (EventType != null)
            {
                if (EventType.Length > 50)
                {
                    throw new ValidationException(ValidationRules.MaxLength, "EventType", 50);
                }
                if (EventType.Length < 0)
                {
                    throw new ValidationException(ValidationRules.MinLength, "EventType", 0);
                }
            }
        }
    }
}
