// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace UiPath.Web.Client20204.Models
{
    using Newtonsoft.Json;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;

    public partial class ItemReviewStatusParameters
    {
        /// <summary>
        /// Initializes a new instance of the ItemReviewStatusParameters class.
        /// </summary>
        public ItemReviewStatusParameters()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the ItemReviewStatusParameters class.
        /// </summary>
        public ItemReviewStatusParameters(string status = default(string), IList<LongVersionedEntity> queueItems = default(IList<LongVersionedEntity>))
        {
            Status = status;
            QueueItems = queueItems;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "status")]
        public string Status { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "queueItems")]
        public IList<LongVersionedEntity> QueueItems { get; set; }

    }
}
