// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace UiPath.Web.Client20204.Models
{
    using Newtonsoft.Json;
    using Newtonsoft.Json.Converters;
    using System.Runtime;
    using System.Runtime.Serialization;

    /// <summary>
    /// Defines values for RobotWithLicenseDtoHostingType.
    /// </summary>
    [JsonConverter(typeof(StringEnumConverter))]
    public enum RobotWithLicenseDtoHostingType
    {
        [EnumMember(Value = "Standard")]
        Standard,
        [EnumMember(Value = "Floating")]
        Floating
    }
    internal static class RobotWithLicenseDtoHostingTypeEnumExtension
    {
        internal static string ToSerializedValue(this RobotWithLicenseDtoHostingType? value)
        {
            return value == null ? null : ((RobotWithLicenseDtoHostingType)value).ToSerializedValue();
        }

        internal static string ToSerializedValue(this RobotWithLicenseDtoHostingType value)
        {
            switch( value )
            {
                case RobotWithLicenseDtoHostingType.Standard:
                    return "Standard";
                case RobotWithLicenseDtoHostingType.Floating:
                    return "Floating";
            }
            return null;
        }

        internal static RobotWithLicenseDtoHostingType? ParseRobotWithLicenseDtoHostingType(this string value)
        {
            switch( value )
            {
                case "Standard":
                    return RobotWithLicenseDtoHostingType.Standard;
                case "Floating":
                    return RobotWithLicenseDtoHostingType.Floating;
            }
            return null;
        }
    }
}
