// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace UiPath.Web.Client20204.Models
{
    using Newtonsoft.Json;
    using Newtonsoft.Json.Converters;
    using System.Runtime;
    using System.Runtime.Serialization;

    /// <summary>
    /// Defines values for WebhookTaskCreatedDtoType.
    /// </summary>
    [JsonConverter(typeof(StringEnumConverter))]
    public enum WebhookTaskCreatedDtoType
    {
        [EnumMember(Value = "DocumentValidationTask")]
        DocumentValidationTask,
        [EnumMember(Value = "ExternalTask")]
        ExternalTask,
        [EnumMember(Value = "FormTask")]
        FormTask
    }
    internal static class WebhookTaskCreatedDtoTypeEnumExtension
    {
        internal static string ToSerializedValue(this WebhookTaskCreatedDtoType? value)
        {
            return value == null ? null : ((WebhookTaskCreatedDtoType)value).ToSerializedValue();
        }

        internal static string ToSerializedValue(this WebhookTaskCreatedDtoType value)
        {
            switch( value )
            {
                case WebhookTaskCreatedDtoType.DocumentValidationTask:
                    return "DocumentValidationTask";
                case WebhookTaskCreatedDtoType.ExternalTask:
                    return "ExternalTask";
                case WebhookTaskCreatedDtoType.FormTask:
                    return "FormTask";
            }
            return null;
        }

        internal static WebhookTaskCreatedDtoType? ParseWebhookTaskCreatedDtoType(this string value)
        {
            switch( value )
            {
                case "DocumentValidationTask":
                    return WebhookTaskCreatedDtoType.DocumentValidationTask;
                case "ExternalTask":
                    return WebhookTaskCreatedDtoType.ExternalTask;
                case "FormTask":
                    return WebhookTaskCreatedDtoType.FormTask;
            }
            return null;
        }
    }
}
