// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace UiPath.Web.Client202010
{
    using Models;
    using System.IO;
    using System.Threading;
    using System.Threading.Tasks;

    /// <summary>
    /// Extension methods for Processes.
    /// </summary>
    public static partial class ProcessesExtensions
    {
            /// <summary>
            /// Gets the processes.
            /// </summary>
            /// <remarks>
            /// Client Credentials Flow required permissions: Execution or Execution.Read.
            ///
            /// Required permissions: (Packages.View - Lists packages in a Tenant Feed) and
            /// (FolderPackages.View - Lists packages in a Folder Feed).
            /// </remarks>
            /// <param name='operations'>
            /// The operations group for this extension method.
            /// </param>
            /// <param name='searchTerm'>
            /// </param>
            /// <param name='feedId'>
            /// </param>
            /// <param name='expand'>
            /// Indicates the related entities to be represented inline. The maximum depth
            /// is 2.
            /// </param>
            /// <param name='filter'>
            /// Restricts the set of items returned. The maximum number of expressions is
            /// 100.
            /// </param>
            /// <param name='select'>
            /// Limits the properties returned in the result.
            /// </param>
            /// <param name='orderby'>
            /// Specifies the order in which items are returned. The maximum number of
            /// expressions is 5.
            /// </param>
            /// <param name='top'>
            /// Limits the number of items returned from a collection. The maximum value is
            /// 1000.
            /// </param>
            /// <param name='skip'>
            /// Excludes the specified number of items of the queried collection from the
            /// result.
            /// </param>
            /// <param name='count'>
            /// Indicates whether the total count of items within a collection are returned
            /// in the result.
            /// </param>
            public static ODataValueOfIEnumerableOfProcessDto Get(this IProcesses operations, string searchTerm = "", System.Guid? feedId = default(System.Guid?), string expand = default(string), string filter = default(string), string select = default(string), string orderby = default(string), int? top = default(int?), int? skip = default(int?), bool? count = default(bool?))
            {
                return operations.GetAsync(searchTerm, feedId, expand, filter, select, orderby, top, skip, count).GetAwaiter().GetResult();
            }

            /// <summary>
            /// Gets the processes.
            /// </summary>
            /// <remarks>
            /// Client Credentials Flow required permissions: Execution or Execution.Read.
            ///
            /// Required permissions: (Packages.View - Lists packages in a Tenant Feed) and
            /// (FolderPackages.View - Lists packages in a Folder Feed).
            /// </remarks>
            /// <param name='operations'>
            /// The operations group for this extension method.
            /// </param>
            /// <param name='searchTerm'>
            /// </param>
            /// <param name='feedId'>
            /// </param>
            /// <param name='expand'>
            /// Indicates the related entities to be represented inline. The maximum depth
            /// is 2.
            /// </param>
            /// <param name='filter'>
            /// Restricts the set of items returned. The maximum number of expressions is
            /// 100.
            /// </param>
            /// <param name='select'>
            /// Limits the properties returned in the result.
            /// </param>
            /// <param name='orderby'>
            /// Specifies the order in which items are returned. The maximum number of
            /// expressions is 5.
            /// </param>
            /// <param name='top'>
            /// Limits the number of items returned from a collection. The maximum value is
            /// 1000.
            /// </param>
            /// <param name='skip'>
            /// Excludes the specified number of items of the queried collection from the
            /// result.
            /// </param>
            /// <param name='count'>
            /// Indicates whether the total count of items within a collection are returned
            /// in the result.
            /// </param>
            /// <param name='cancellationToken'>
            /// The cancellation token.
            /// </param>
            public static async Task<ODataValueOfIEnumerableOfProcessDto> GetAsync(this IProcesses operations, string searchTerm = "", System.Guid? feedId = default(System.Guid?), string expand = default(string), string filter = default(string), string select = default(string), string orderby = default(string), int? top = default(int?), int? skip = default(int?), bool? count = default(bool?), CancellationToken cancellationToken = default(CancellationToken))
            {
                using (var _result = await operations.GetWithHttpMessagesAsync(searchTerm, feedId, expand, filter, select, orderby, top, skip, count, null, cancellationToken).ConfigureAwait(false))
                {
                    return _result.Body;
                }
            }

            /// <summary>
            /// Deletes a package.
            /// </summary>
            /// <remarks>
            /// Client Credentials Flow required permissions: Execution or Execution.Write.
            ///
            /// Required permissions: (Packages.Delete - Deletes a package in a Tenant
            /// Feed) and (FolderPackages.Delete - Deletes a package in a Folder Feed).
            /// </remarks>
            /// <param name='operations'>
            /// The operations group for this extension method.
            /// </param>
            /// <param name='key'>
            /// </param>
            /// <param name='feedId'>
            /// </param>
            public static void DeleteById(this IProcesses operations, string key, System.Guid? feedId = default(System.Guid?))
            {
                operations.DeleteByIdAsync(key, feedId).GetAwaiter().GetResult();
            }

            /// <summary>
            /// Deletes a package.
            /// </summary>
            /// <remarks>
            /// Client Credentials Flow required permissions: Execution or Execution.Write.
            ///
            /// Required permissions: (Packages.Delete - Deletes a package in a Tenant
            /// Feed) and (FolderPackages.Delete - Deletes a package in a Folder Feed).
            /// </remarks>
            /// <param name='operations'>
            /// The operations group for this extension method.
            /// </param>
            /// <param name='key'>
            /// </param>
            /// <param name='feedId'>
            /// </param>
            /// <param name='cancellationToken'>
            /// The cancellation token.
            /// </param>
            public static async Task DeleteByIdAsync(this IProcesses operations, string key, System.Guid? feedId = default(System.Guid?), CancellationToken cancellationToken = default(CancellationToken))
            {
                (await operations.DeleteByIdWithHttpMessagesAsync(key, feedId, null, cancellationToken).ConfigureAwait(false)).Dispose();
            }

            /// <summary>
            /// Downloads the .nupkg file of a Package.
            /// </summary>
            /// <remarks>
            /// Client Credentials Flow required permissions: Execution or Execution.Read.
            ///
            /// Required permissions: (Packages.View - Downloads a package from a Tenant
            /// Feed) and (FolderPackages.View - Downloads a package from a Folder Feed).
            /// </remarks>
            /// <param name='operations'>
            /// The operations group for this extension method.
            /// </param>
            /// <param name='key'>
            /// </param>
            /// <param name='feedId'>
            /// </param>
            public static Stream DownloadPackageByKey(this IProcesses operations, string key, System.Guid? feedId = default(System.Guid?))
            {
                return operations.DownloadPackageByKeyAsync(key, feedId).GetAwaiter().GetResult();
            }

            /// <summary>
            /// Downloads the .nupkg file of a Package.
            /// </summary>
            /// <remarks>
            /// Client Credentials Flow required permissions: Execution or Execution.Read.
            ///
            /// Required permissions: (Packages.View - Downloads a package from a Tenant
            /// Feed) and (FolderPackages.View - Downloads a package from a Folder Feed).
            /// </remarks>
            /// <param name='operations'>
            /// The operations group for this extension method.
            /// </param>
            /// <param name='key'>
            /// </param>
            /// <param name='feedId'>
            /// </param>
            /// <param name='cancellationToken'>
            /// The cancellation token.
            /// </param>
            public static async Task<Stream> DownloadPackageByKeyAsync(this IProcesses operations, string key, System.Guid? feedId = default(System.Guid?), CancellationToken cancellationToken = default(CancellationToken))
            {
                var _result = await operations.DownloadPackageByKeyWithHttpMessagesAsync(key, feedId, null, cancellationToken).ConfigureAwait(false);
                _result.Request.Dispose();
                return _result.Body;
            }

            /// <summary>
            /// Get process parameters
            /// </summary>
            /// <remarks>
            /// Client Credentials Flow required permissions: Execution or Execution.Read.
            ///
            /// Required permissions: Packages.View.
            /// </remarks>
            /// <param name='operations'>
            /// The operations group for this extension method.
            /// </param>
            /// <param name='key'>
            /// </param>
            /// <param name='expand'>
            /// Indicates the related entities to be represented inline. The maximum depth
            /// is 2.
            /// </param>
            /// <param name='select'>
            /// Limits the properties returned in the result.
            /// </param>
            public static ArgumentMetadata GetArgumentsByKey(this IProcesses operations, string key, string expand = default(string), string select = default(string))
            {
                return operations.GetArgumentsByKeyAsync(key, expand, select).GetAwaiter().GetResult();
            }

            /// <summary>
            /// Get process parameters
            /// </summary>
            /// <remarks>
            /// Client Credentials Flow required permissions: Execution or Execution.Read.
            ///
            /// Required permissions: Packages.View.
            /// </remarks>
            /// <param name='operations'>
            /// The operations group for this extension method.
            /// </param>
            /// <param name='key'>
            /// </param>
            /// <param name='expand'>
            /// Indicates the related entities to be represented inline. The maximum depth
            /// is 2.
            /// </param>
            /// <param name='select'>
            /// Limits the properties returned in the result.
            /// </param>
            /// <param name='cancellationToken'>
            /// The cancellation token.
            /// </param>
            public static async Task<ArgumentMetadata> GetArgumentsByKeyAsync(this IProcesses operations, string key, string expand = default(string), string select = default(string), CancellationToken cancellationToken = default(CancellationToken))
            {
                using (var _result = await operations.GetArgumentsByKeyWithHttpMessagesAsync(key, expand, select, null, cancellationToken).ConfigureAwait(false))
                {
                    return _result.Body;
                }
            }

            /// <summary>
            /// Returns a collection of all available versions of a given process. Allows
            /// odata query options.
            /// </summary>
            /// <remarks>
            /// Client Credentials Flow required permissions: Execution or Execution.Read.
            ///
            /// Required permissions: (Packages.View - Lists versions of a package in a
            /// Tenant Feed) and (FolderPackages.View - Lists versions of a package in a
            /// Folder Feed).
            /// </remarks>
            /// <param name='operations'>
            /// The operations group for this extension method.
            /// </param>
            /// <param name='processId'>
            /// The Id of the process for which the versions are fetched.
            /// </param>
            /// <param name='feedId'>
            /// </param>
            /// <param name='expand'>
            /// Indicates the related entities to be represented inline. The maximum depth
            /// is 2.
            /// </param>
            /// <param name='filter'>
            /// Restricts the set of items returned. The maximum number of expressions is
            /// 100.
            /// </param>
            /// <param name='select'>
            /// Limits the properties returned in the result.
            /// </param>
            /// <param name='orderby'>
            /// Specifies the order in which items are returned. The maximum number of
            /// expressions is 5.
            /// </param>
            /// <param name='top'>
            /// Limits the number of items returned from a collection. The maximum value is
            /// 1000.
            /// </param>
            /// <param name='skip'>
            /// Excludes the specified number of items of the queried collection from the
            /// result.
            /// </param>
            /// <param name='count'>
            /// Indicates whether the total count of items within a collection are returned
            /// in the result.
            /// </param>
            public static ODataValueOfIEnumerableOfProcessDto GetProcessVersionsByProcessid(this IProcesses operations, string processId, System.Guid? feedId = default(System.Guid?), string expand = default(string), string filter = default(string), string select = default(string), string orderby = default(string), int? top = default(int?), int? skip = default(int?), bool? count = default(bool?))
            {
                return operations.GetProcessVersionsByProcessidAsync(processId, feedId, expand, filter, select, orderby, top, skip, count).GetAwaiter().GetResult();
            }

            /// <summary>
            /// Returns a collection of all available versions of a given process. Allows
            /// odata query options.
            /// </summary>
            /// <remarks>
            /// Client Credentials Flow required permissions: Execution or Execution.Read.
            ///
            /// Required permissions: (Packages.View - Lists versions of a package in a
            /// Tenant Feed) and (FolderPackages.View - Lists versions of a package in a
            /// Folder Feed).
            /// </remarks>
            /// <param name='operations'>
            /// The operations group for this extension method.
            /// </param>
            /// <param name='processId'>
            /// The Id of the process for which the versions are fetched.
            /// </param>
            /// <param name='feedId'>
            /// </param>
            /// <param name='expand'>
            /// Indicates the related entities to be represented inline. The maximum depth
            /// is 2.
            /// </param>
            /// <param name='filter'>
            /// Restricts the set of items returned. The maximum number of expressions is
            /// 100.
            /// </param>
            /// <param name='select'>
            /// Limits the properties returned in the result.
            /// </param>
            /// <param name='orderby'>
            /// Specifies the order in which items are returned. The maximum number of
            /// expressions is 5.
            /// </param>
            /// <param name='top'>
            /// Limits the number of items returned from a collection. The maximum value is
            /// 1000.
            /// </param>
            /// <param name='skip'>
            /// Excludes the specified number of items of the queried collection from the
            /// result.
            /// </param>
            /// <param name='count'>
            /// Indicates whether the total count of items within a collection are returned
            /// in the result.
            /// </param>
            /// <param name='cancellationToken'>
            /// The cancellation token.
            /// </param>
            public static async Task<ODataValueOfIEnumerableOfProcessDto> GetProcessVersionsByProcessidAsync(this IProcesses operations, string processId, System.Guid? feedId = default(System.Guid?), string expand = default(string), string filter = default(string), string select = default(string), string orderby = default(string), int? top = default(int?), int? skip = default(int?), bool? count = default(bool?), CancellationToken cancellationToken = default(CancellationToken))
            {
                using (var _result = await operations.GetProcessVersionsByProcessidWithHttpMessagesAsync(processId, feedId, expand, filter, select, orderby, top, skip, count, null, cancellationToken).ConfigureAwait(false))
                {
                    return _result.Body;
                }
            }

            /// <summary>
            /// Saves process arguments
            /// </summary>
            /// <remarks>
            /// Client Credentials Flow required permissions: Execution or Execution.Write.
            ///
            /// Required permissions: Packages.Edit.
            /// </remarks>
            /// <param name='operations'>
            /// The operations group for this extension method.
            /// </param>
            /// <param name='body'>
            /// </param>
            public static void SetArguments(this IProcesses operations, ProcessesSetArgumentsParameters body = default(ProcessesSetArgumentsParameters))
            {
                operations.SetArgumentsAsync(body).GetAwaiter().GetResult();
            }

            /// <summary>
            /// Saves process arguments
            /// </summary>
            /// <remarks>
            /// Client Credentials Flow required permissions: Execution or Execution.Write.
            ///
            /// Required permissions: Packages.Edit.
            /// </remarks>
            /// <param name='operations'>
            /// The operations group for this extension method.
            /// </param>
            /// <param name='body'>
            /// </param>
            /// <param name='cancellationToken'>
            /// The cancellation token.
            /// </param>
            public static async Task SetArgumentsAsync(this IProcesses operations, ProcessesSetArgumentsParameters body = default(ProcessesSetArgumentsParameters), CancellationToken cancellationToken = default(CancellationToken))
            {
                (await operations.SetArgumentsWithHttpMessagesAsync(body, null, cancellationToken).ConfigureAwait(false)).Dispose();
            }

            /// <summary>
            /// Uploads a new package or a new version of an existing package. The content
            /// of the package is sent as a .nupkg file embedded in the HTTP request.
            /// </summary>
            /// <remarks>
            /// Client Credentials Flow required permissions: Execution or Execution.Write.
            ///
            /// Required permissions: (Packages.Create - Uploads a package in a Tenant
            /// Feed) and (FolderPackages.Create - Uploads a package in a Folder Feed).
            /// </remarks>
            /// <param name='operations'>
            /// The operations group for this extension method.
            /// </param>
            /// <param name='file'>
            /// </param>
            /// <param name='feedId'>
            /// </param>
            /// <param name='expand'>
            /// Indicates the related entities to be represented inline. The maximum depth
            /// is 2.
            /// </param>
            /// <param name='filter'>
            /// Restricts the set of items returned. The maximum number of expressions is
            /// 100.
            /// </param>
            /// <param name='select'>
            /// Limits the properties returned in the result.
            /// </param>
            /// <param name='orderby'>
            /// Specifies the order in which items are returned. The maximum number of
            /// expressions is 5.
            /// </param>
            /// <param name='count'>
            /// Indicates whether the total count of items within a collection are returned
            /// in the result.
            /// </param>
            /// <param name='file1'>
            /// </param>
            /// <param name='file2'>
            /// </param>
            /// <param name='file3'>
            /// </param>
            /// <param name='file4'>
            /// </param>
            /// <param name='file5'>
            /// </param>
            /// <param name='file6'>
            /// </param>
            /// <param name='file7'>
            /// </param>
            /// <param name='file8'>
            /// </param>
            /// <param name='file9'>
            /// </param>
            public static ODataValueOfIEnumerableOfBulkItemDtoOfString UploadPackage(this IProcesses operations, Stream file, System.Guid? feedId = default(System.Guid?), string expand = default(string), string filter = default(string), string select = default(string), string orderby = default(string), bool? count = default(bool?), Stream file1 = default(Stream), Stream file2 = default(Stream), Stream file3 = default(Stream), Stream file4 = default(Stream), Stream file5 = default(Stream), Stream file6 = default(Stream), Stream file7 = default(Stream), Stream file8 = default(Stream), Stream file9 = default(Stream))
            {
                return operations.UploadPackageAsync(file, feedId, expand, filter, select, orderby, count, file1, file2, file3, file4, file5, file6, file7, file8, file9).GetAwaiter().GetResult();
            }

            /// <summary>
            /// Uploads a new package or a new version of an existing package. The content
            /// of the package is sent as a .nupkg file embedded in the HTTP request.
            /// </summary>
            /// <remarks>
            /// Client Credentials Flow required permissions: Execution or Execution.Write.
            ///
            /// Required permissions: (Packages.Create - Uploads a package in a Tenant
            /// Feed) and (FolderPackages.Create - Uploads a package in a Folder Feed).
            /// </remarks>
            /// <param name='operations'>
            /// The operations group for this extension method.
            /// </param>
            /// <param name='file'>
            /// </param>
            /// <param name='feedId'>
            /// </param>
            /// <param name='expand'>
            /// Indicates the related entities to be represented inline. The maximum depth
            /// is 2.
            /// </param>
            /// <param name='filter'>
            /// Restricts the set of items returned. The maximum number of expressions is
            /// 100.
            /// </param>
            /// <param name='select'>
            /// Limits the properties returned in the result.
            /// </param>
            /// <param name='orderby'>
            /// Specifies the order in which items are returned. The maximum number of
            /// expressions is 5.
            /// </param>
            /// <param name='count'>
            /// Indicates whether the total count of items within a collection are returned
            /// in the result.
            /// </param>
            /// <param name='file1'>
            /// </param>
            /// <param name='file2'>
            /// </param>
            /// <param name='file3'>
            /// </param>
            /// <param name='file4'>
            /// </param>
            /// <param name='file5'>
            /// </param>
            /// <param name='file6'>
            /// </param>
            /// <param name='file7'>
            /// </param>
            /// <param name='file8'>
            /// </param>
            /// <param name='file9'>
            /// </param>
            /// <param name='cancellationToken'>
            /// The cancellation token.
            /// </param>
            public static async Task<ODataValueOfIEnumerableOfBulkItemDtoOfString> UploadPackageAsync(this IProcesses operations, Stream file, System.Guid? feedId = default(System.Guid?), string expand = default(string), string filter = default(string), string select = default(string), string orderby = default(string), bool? count = default(bool?), Stream file1 = default(Stream), Stream file2 = default(Stream), Stream file3 = default(Stream), Stream file4 = default(Stream), Stream file5 = default(Stream), Stream file6 = default(Stream), Stream file7 = default(Stream), Stream file8 = default(Stream), Stream file9 = default(Stream), CancellationToken cancellationToken = default(CancellationToken))
            {
                using (var _result = await operations.UploadPackageWithHttpMessagesAsync(file, feedId, expand, filter, select, orderby, count, file1, file2, file3, file4, file5, file6, file7, file8, file9, null, cancellationToken).ConfigureAwait(false))
                {
                    return _result.Body;
                }
            }

    }
}
