// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace UiPath.Web.Client201910.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    public partial class ApplyQueryOption
    {
        /// <summary>
        /// Initializes a new instance of the ApplyQueryOption class.
        /// </summary>
        public ApplyQueryOption()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the ApplyQueryOption class.
        /// </summary>
        public ApplyQueryOption(ODataQueryContext context = default(ODataQueryContext), string resultClrType = default(string), ApplyClause applyClause = default(ApplyClause), string rawValue = default(string))
        {
            Context = context;
            ResultClrType = resultClrType;
            ApplyClause = applyClause;
            RawValue = rawValue;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Context")]
        public ODataQueryContext Context { get; private set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "ResultClrType")]
        public string ResultClrType { get; private set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "ApplyClause")]
        public ApplyClause ApplyClause { get; private set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "RawValue")]
        public string RawValue { get; private set; }

    }
}
