// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace UiPath.Web.Client201910.Models
{
    using Newtonsoft.Json;
    using Newtonsoft.Json.Converters;
    using System.Runtime;
    using System.Runtime.Serialization;

    /// <summary>
    /// Defines values for FormTaskCreateRequestPriority.
    /// </summary>
    [JsonConverter(typeof(StringEnumConverter))]
    public enum FormTaskCreateRequestPriority
    {
        [EnumMember(Value = "Low")]
        Low,
        [EnumMember(Value = "Medium")]
        Medium,
        [EnumMember(Value = "High")]
        High,
        [EnumMember(Value = "Critical")]
        Critical
    }
    internal static class FormTaskCreateRequestPriorityEnumExtension
    {
        internal static string ToSerializedValue(this FormTaskCreateRequestPriority? value)
        {
            return value == null ? null : ((FormTaskCreateRequestPriority)value).ToSerializedValue();
        }

        internal static string ToSerializedValue(this FormTaskCreateRequestPriority value)
        {
            switch( value )
            {
                case FormTaskCreateRequestPriority.Low:
                    return "Low";
                case FormTaskCreateRequestPriority.Medium:
                    return "Medium";
                case FormTaskCreateRequestPriority.High:
                    return "High";
                case FormTaskCreateRequestPriority.Critical:
                    return "Critical";
            }
            return null;
        }

        internal static FormTaskCreateRequestPriority? ParseFormTaskCreateRequestPriority(this string value)
        {
            switch( value )
            {
                case "Low":
                    return FormTaskCreateRequestPriority.Low;
                case "Medium":
                    return FormTaskCreateRequestPriority.Medium;
                case "High":
                    return FormTaskCreateRequestPriority.High;
                case "Critical":
                    return FormTaskCreateRequestPriority.Critical;
            }
            return null;
        }
    }
}
